### ISSUE TITLE
Warning while installing lara-asp

### ISSUE THREAD

**Issue by webard** [LastDragon-ru/lara-asp#107]
Hello,

After execute there is warning `composer require lastdragon-ru/lara-asp-graphql`:
<img width="752" alt="image" src="https://github.com/LastDragon-ru/lara-asp/assets/855788/94c6c15f-3453-4198-8211-055e2c6d8d02">

```
Failed to extract lastdragon-ru/lara-asp-graphql: (50) '/usr/bin/unzip' -qq '/Users/bgajda/Praca/sylapi/sylconnect/vendor/composer/tmp-777ee17b4c646e43e1e1649b23f1e9b2' -d '/Users/bgajda/Praca/sylapi/sylconnect/vendor/composer/262c10e2'

error:  cannot create /Users/bgajda/Praca/sylapi/sylconnect/vendor/composer/262c10e2/LastDragon-ru-lara-asp-graphql-6e42fc1/src/SearchBy/Directives/DirectiveTest~full-expected-scout���10.3.0.graphql
        Illegal byte sequence

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class
```

Looks like something is wrong with this file: `LastDragon-ru-lara-asp-graphql-6e42fc1/src/SearchBy/Directives/DirectiveTest~full-expected-scout���10.3.0.graphql` and only ZipArchive can extract archive.

Version of composer: 2.6.6
Version of /usr/bin/unzip:  UnZip 6.00 of 20 April 2009

**Comment by LastDragon-ru** [comment]
Thank for the report. Related to `unzip`. Should be fixed in [v5.3.1](https://github.com/LastDragon-ru/lara-asp/releases/tag/5.3.1)
