### ISSUE TITLE
"_" type with @sortBy directive does not work with @paginate lighthouse directive

### ISSUE THREAD

**Issue by webard** [LastDragon-ru/lara-asp#12]
Hi,

when I use @sortBy (or @searchBy) with auto generated type "_", I get error:
```
Impossible to create Sort Clause for `type CategoryPaginator`
```

with @all directive, everything works fine. Seems like @sortBy and @searchBy does not support paginators.

**Comment by LastDragon-ru** [comment]
The `@searchBy` directive is not yet supported `_`, the `@sortby` should work now.
