### ISSUE TITLE
How do I searchBy in range for date?

### ISSUE THREAD

**Issue by truesteps** [LastDragon-ru/lara-asp#124]
Hey!

I've been stuck on this one, I am using your graphql extensions and i'm trying to search a range of dates, in the documentation you do search between dates, but whenever I try to do so, I get the error, that the `SearchByScoutScalarDate` doesn't implement between, it only has equal.

I tried to add @searchByOperatorBetween onto my scalar for Date from lighthouse-php or even @searchByOperators(type: "Int") but nothing seems to make this work.

Could you please clear it up for me?

In the examples of the [@searchBy.md](https://github.com/LastDragon-ru/lara-asp-graphql/blob/main/docs/Directives/@searchBy.md) file you show searching in date range for a relationship.

```GraphQL
scalar Date @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\Date") @searchByOperators(type: "Int")

input FilterCreatedAt {
	created_at: Date!
}

ScoutPaginated(
	search: String! @search
	created_at: FilterCreatedAt @searchBy
) [User!] @paginate(defaultCount: 30)
```

Thanks,
Patrik.

**Comment by LastDragon-ru** [comment]
Looks like you are using Laravel Scout. Unfortunately, Scout supports only simple operators: `equal`, `in` and `notIn` (since v10.3.0).

**Comment by truesteps** [comment]
Oh! The docs say scout is supported :D so if I understand correctly, the directive only appplies to the eloquent/query builder not the scout builder?

**Comment by LastDragon-ru** [comment]
> Scout supports only simple operators: equal, in and notIn (since v10.3.0).

This is the Scout limitation (not the `@searchBy`), the Scout `Builder` class provides only [three methods to search](https://github.com/laravel/scout/blob/942056273b69518756351359c035763969571cff/src/Builder.php#L126-L166). So only these three operators are available if you are using it. 

The `Between` operator is available for Query and Eloquent builders.

**Comment by truesteps** [comment]
I understand :) thanks a bunch!
