### ISSUE TITLE
Printing schema not works: Type `CanAction` not found in the Schema.

### ISSUE THREAD

**Issue by webard** [LastDragon-ru/lara-asp#155]
Hello,

I have latest version of Laravel, Lighthouse and Lara ASP.  I have simple code that prints schema in SDL:

```php
Route::get('/graphql-sdl', static function (): string {
    $schema = Container::getInstance()->make(SchemaBuilder::class)->schema();
    $printer = Container::getInstance()->make(Printer::class);
    $printed = $printer->print($schema);

    return (string) $printed;
});
```
but that code generates error:
```
LastDragon_ru \ LaraASP \ GraphQLPrinter \ Exceptions \ TypeNotFound

Type `CanAction` not found in the Schema.
```

But this type should be registered by Lighthouse: https://lighthouse-php.com/6/api-reference/directives.html#can-family-of-directives.

There is no info in Lighthouse docs about adding additional ServiceProvider or something.

**Comment by LastDragon-ru** [comment]
> Laravel, Lighthouse and Lara ASP

What versions are you using?

**Comment by LastDragon-ru** [comment]
For the first look, it seems lighthouse issue. The `CanAction` type defined in [`BaseCanDirective::commonTypes()`](https://github.com/nuwave/lighthouse/blob/c6748470694afb08ac424afa1308282519a9bd03/src/Auth/BaseCanDirective.php#L53-L78), but the method called in [`CanFindDirective::definition()`](https://github.com/nuwave/lighthouse/blob/c6748470694afb08ac424afa1308282519a9bd03/src/Auth/CanFindDirective.php#L23-L26) only. So seems if `@canFind` directive is not used in the schema, the type will never add to the schema.

**Comment by LastDragon-ru** [comment]
As workaround you can try (not tested)

```php
Route::get('/graphql-sdl', static function (): string {
    // Will load all types from the directive
    $resolver = Container::getInstance()->make(\LastDragon_ru\LaraASP\GraphQLPrinter\Contracts\DirectiveResolver::class);
    $resolver->getDefinition('@canFind');
    // end

    $schema  = Container::getInstance()->make(SchemaBuilder::class)->schema();
    $printer = Container::getInstance()->make(Printer::class);
    $printed = $printer->print($schema);

    return (string) $printed;
});
```

**Comment by webard** [comment]
> if `@canFind` directive is not used in the schema, the type will never add to the schema.

I don't use this directive, so why Schema Printer require type definitions for this directive?

**Comment by LastDragon-ru** [comment]
Because only this directive will add `CanAction` type definition)

**Comment by LastDragon-ru** [comment]
As I said it is related how Lighthouse adds/loads own types.
