### ISSUE TITLE
Publish lara-asp-graphql-printer on packagist.org

### ISSUE THREAD

**Issue by webard** [LastDragon-ru/lara-asp#67]
Hi,
Your awesome package lara-asp-graphql-printer is not available on packagist (https://packagist.org/packages/lastdragon-ru/), so installing it is unnecessary complicated using 

```
{
            "type": "vcs",
            "url": "https://github.com/LastDragon-ru/lara-asp-graphql-printer.git"
}
```

in composer.json

**Comment by LastDragon-ru** [comment]
https://packagist.org/packages/lastdragon-ru/lara-asp-graphql-printer fixed, thanks :)
