### ISSUE TITLE
Fails in combination with `Node` interface

### ISSUE THREAD

**Issue by jaulz** [LastDragon-ru/lara-asp#73]
In my application I am adding the `Node` interface via a custom directive:
```php
    $nodeType = Parser::parseType(GlobalIdServiceProvider::NODE, [
      'noLocation' => true,
    ]);
    assert($nodeType instanceof NamedTypeNode);
    $objectType->interfaces[] = $nodeType;
```

Unfortunately, this causes issues in this call because the `Node` interface is not yet known:
![image](https://user-images.githubusercontent.com/5358638/232042607-2fa834ac-ddfd-4bea-8162-96609e4a572b.png)

The `Node` interface is only available later on:
https://github.com/nuwave/lighthouse/blob/d4ea07d61f1a0254bc979ab0d20ab33730edbd85/src/GlobalId/GlobalIdServiceProvider.php#L28-L37

**Comment by LastDragon-ru** [comment]
Do you mean "TypeDefinitionUnknown: Type Definition `Node` is not defined." error? This is expected - type should be known before transformation, because types of the fields may not be updated correctly and the schema will be invalid :(

You can try to override `GlobalIdServiceProvide` to call `GlobalIdServiceProvider::addNodeSupport()` manually before transformation. Or you can define `input` with required (same) fields without the `GlobalIdServiceProvider::NODE` interface and use it as argument type: `field(where: MyInput @searchBy): MyType`). 

Maybe @spawnia can suggest something too.

**Comment by spawnia** [comment]
> this call

Which call? Where?

**Comment by LastDragon-ru** [comment]
If I understand the issue correctly: when `@node` used it will automatically add interface `Node`, but the `Node` is not available in the schema yet (it will be added later via `GlobalIdServiceProvider`) and `@searchBy`/`@sortBy` will fail:

```graphql
type Query {
  users(where: _ @searchBy): [User!] @all
}

type User @node {
  id: ID! @globalId
}
```

@jaulz , right?

**Comment by jaulz** [comment]
@LastDragon-ru almost... except for that the query is on another type, something like this:
```graphql
type Query {
  users: [User!] @all
}

type User @node {
  id: ID! @globalId
  emails(where: _ @searchBy): [Email!] @all
}

type Email @node {
  id: ID! @globalId
}
```

@spawnia sorry, "this call" referred to the screenshot and is about `getNodeInterfaces`: https://github.com/LastDragon-ru/lara-asp/blob/4e0b2abda5850766bc8feb25c8e3ab876ce4c9ce/packages/graphql/src/Builder/Directives/HandlerDirective.php#L242 

It reads the interfaces of the given node and expects them to already exist. 

So yeah, I could of course register the type manually before but I thought that it would not be the optimal solution 😊

**Comment by LastDragon-ru** [comment]
> which is the parent node!

Otherwise it will fail if

```graphql
type User implements UserInterface {
  emails(where: _ @searchBy): [Email!] @all
}

interface UserInterface {
  emails(where: _): [Email!] # <-- fields will be incompatible
}
```

> Or you can define input with required (same) fields without the GlobalIdServiceProvider::NODE interface

Seems it will not work :(

**Comment by spawnia** [comment]
Fix released with https://github.com/nuwave/lighthouse/releases/tag/v6.6.1.

**Comment by LastDragon-ru** [comment]
@spawnia thank you :)
