### ISSUE TITLE
Automatically convert camel case fields to snake case

### ISSUE THREAD

**Issue by jaulz** [LastDragon-ru/lara-asp#87]
It would be great if there would be a way to automatically rename fields in the type that is used with the `@searchBy` directive to be in snake case. For example I would like to leave out the `@rename` column here:
```gql
input LegalEntityTypeFilters {
  title: String
  countryCode: String @rename(attribute: "country_code")
}
```

Or is there any nice way at the moment to already achieve it?

**Comment by jaulz** [comment]
While doing the mentioned renaming above, I noticed that it actually doesn't work like the way I thought. There is no filter applied eventually 🤔

**Comment by LastDragon-ru** [comment]
> Or is there any nice way at the moment to already achieve it?

Nope...

> There is no filter applied eventually 🤔

Strange. (1) Which version of the package are you using? (2) Do you see `@rename` in the final schema?

ps: You can also try https://github.com/itsgoingd/clockwork / https://laravel.com/docs/10.x/telescope to see queries.

**Comment by jaulz** [comment]
I am using 4.5.0 and actually just upgraded. However, I think I found where the value is lost:
<img width="790" alt="image" src="https://github.com/LastDragon-ru/lara-asp/assets/5358638/09e7f4f2-6e42-4073-b7d7-046e0e9b3382">

The input is still `country_code` but the type's property is `countryCode` and hence the arguments are empty and the filter is not applied:
<img width="618" alt="image" src="https://github.com/LastDragon-ru/lara-asp/assets/5358638/72814b71-db61-4069-9039-774e36ca4bc0">

**Comment by LastDragon-ru** [comment]
Maybe you can create a small repo with the error? It will be very helpful for debug.

**Comment by LastDragon-ru** [comment]
> I think I found where the value is lost:

Yep. I can reproduce it, but not sure how to fix yet. The bug extracted to #88.

**Comment by LastDragon-ru** [comment]
In upcoming v6 will be possible to define [`BuilderPropertyResolver`](./src/Builder/Contracts/BuilderPropertyResolver.php) and implement any conversion you want 😃

```php
// AppProvider

$this->app->bind(
    LastDragon_ru\LaraASP\GraphQL\Builder\Contracts\BuilderPropertyResolver::class,
    MyBuilderPropertyResolver::class,
);
```
