### ISSUE TITLE
`@rename` doesn't work as expected: no filters

### ISSUE THREAD

**Issue by LastDragon-ru** [LastDragon-ru/lara-asp#88]
> I am using 4.5.0 and actually just upgraded. However, I think I found where the value is lost:
> <img width="790" alt="image" src="https://github.com/LastDragon-ru/lara-asp/assets/5358638/09e7f4f2-6e42-4073-b7d7-046e0e9b3382">
> 
> The input is still `country_code` but the type's property is `countryCode` and hence the arguments are empty and the filter is not applied:
> <img width="618" alt="image" src="https://github.com/LastDragon-ru/lara-asp/assets/5358638/72814b71-db61-4069-9039-774e36ca4bc0">

_Originally posted by @jaulz in https://github.com/LastDragon-ru/lara-asp/issues/87#issuecomment-1656837905_

**Comment by LastDragon-ru** [comment]
The problem is the `$value` passed into `ArgBuilderDirective::handleBuilder()` contains renamed properties, not the original. Thus, we cannot create the valid `Argument`.

The second problem: the tests are ok.

**Comment by jaulz** [comment]
Yeah, I was also wondering why the tests were running fine but I could not trace it down yet. While running the tests, `$value` actually contains the unrenamed keys.

**Comment by jaulz** [comment]
Why do we need the `getArgumentSet` at all? 🤔 Wouldn't it just convert the property names back and forth?

**Comment by LastDragon-ru** [comment]
> Why do we need the getArgumentSet at all?

To work directly with directives which also allows to add operators inside the schema, it is also allow create complex queries like #11. 

Seems I have an idea... I will try to create PR for lighthouse within a few days. If it will be accepted the `Argument` will be passed directly into `ArgBuilderDirective` that should resolve the issue.

**Comment by jaulz** [comment]
Great, sounds good. Thanks for the library and your efforts! ✌️

**Comment by LastDragon-ru** [comment]
Should be fixed in [v4.5.1](https://github.com/LastDragon-ru/lara-asp/releases/tag/4.5.1), please try
